development:
  adapter: postgresql
  database: jovens_da_paz_development
  username: jpedro
  password: 102030
  host: localhost
  port: 5432
  pool: 5

production:
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: 20
