default: &default
  adapter: postgresql
  template: template0
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: jovens_da_paz_development

test:
  <<: *default
  database: jovens_da_paz_test

production:
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: 20
